services:
  vaultwarden:
    image: vaultwarden/server:1.37.2
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      - DOMAIN=https://vaultwarden.${DOMAIN}
      - SIGNUPS_ALLOWED=true # después de crear tu cuenta, cerrá registros
      - WEBSOCKET_ENABLED=true
      - ADMIN_TOKEN=${ADMIN_TOKEN}
    volumes:
      - ./data:/data
    networks:
      - proxy
networks:
  proxy:
    external: true
